// Generated by ego.
// DO NOT EDIT

//line template/error.ego:1
package template

import "fmt"
import "html"
import "io"
import "context"

import (
	. "github.com/benbjohnson/tiny-ego/http/component"
)

type ErrorTemplate struct {
	Err error
}

func (tmpl *ErrorTemplate) Render(ctx context.Context, w io.Writer) {

//line template/error.ego:15
	{
		egoComponent := App{
			Title: "Home",
			Yield: func() {
//line template/error.ego:16
				{
					egoComponent := Error{
						Err: tmpl.Err,
					}
					egoComponent.Render(ctx, w)
				}
			},
		}
		egoComponent.Render(ctx, w)
	}
//line template/error.ego:19
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
