// Generated by ego.
// DO NOT EDIT

//line template/index.ego:1
package template

import "fmt"
import "html"
import "io"
import "context"

import (
	. "github.com/benbjohnson/tiny-ego/http/component"
)

type IndexTemplate struct{}

func (tmpl *IndexTemplate) Render(ctx context.Context, w io.Writer) {

//line template/index.ego:13
	{
		egoComponent := App{
			Title: "Home",
			Yield: func() {
//line template/index.ego:14
				_, _ = io.WriteString(w, "<p>\n\t\tHello and welcome to ACME Corp!\n\t</p>\n")
			},
		}
		egoComponent.Render(ctx, w)
	}
//line template/index.ego:19
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
