// Generated by ego.
// DO NOT EDIT

//line template/widget.index.ego:1
package template

import "fmt"
import "html"
import "io"
import "context"

import (
	"github.com/benbjohnson/tiny-ego"
	. "github.com/benbjohnson/tiny-ego/http/component"
)

type WidgetIndexTemplate struct {
	Widgets []*tinyego.Widget
	Filter  tinyego.WidgetFilter
}

func (tmpl *WidgetIndexTemplate) Render(ctx context.Context, w io.Writer) {

//line template/widget.index.ego:16
	{
		egoComponent := App{
			Title: "Widgets",
			Yield: func() {
//line template/widget.index.ego:17
				{
					egoComponent := SearchBar{
						Yield: func() {
//line template/widget.index.ego:18
							{
								egoComponent := SearchField{
									Label: "Keyword",
									Yield: func() {
//line template/widget.index.ego:19
										_, _ = io.WriteString(w, "<input name=\"q\" value=\"")
//line template/widget.index.ego:19
										_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(formatStringPtr(tmpl.Filter.Query))))
//line template/widget.index.ego:19
										_, _ = io.WriteString(w, "\"/>\n\t\t")
									},
								}
								egoComponent.Render(ctx, w)
							}
//line template/widget.index.ego:22
							{
								egoComponent := SearchField{
									Label: "Keyword",
									Yield: func() {
//line template/widget.index.ego:23
										_, _ = io.WriteString(w, "<input name=\"q\" value=\"")
//line template/widget.index.ego:23
										_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(formatStringPtr(tmpl.Filter.Query))))
//line template/widget.index.ego:23
										_, _ = io.WriteString(w, "\"/>\n\t\t")
									},
								}
								egoComponent.Render(ctx, w)
							}
						},
					}
					egoComponent.Render(ctx, w)
				}
//line template/widget.index.ego:27
				if len(tmpl.Widgets) == 0 {
//line template/widget.index.ego:28
					{
						egoComponent := Alert{
							Style: "info",
							Yield: func() {
//line template/widget.index.ego:29
								_, _ = io.WriteString(w, "No widgets found.\n\t\t")
							},
						}
						egoComponent.Render(ctx, w)
					}
//line template/widget.index.ego:31
				} else {
//line template/widget.index.ego:32
					_, _ = io.WriteString(w, "<!-- TODO: Table -->\n\t")
//line template/widget.index.ego:33
				}
			},
		}
		egoComponent.Render(ctx, w)
	}
//line template/widget.index.ego:35
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
