// Generated by ego.
// DO NOT EDIT

//line http/component/alert.ego:1
package component

import "fmt"
import "html"
import "io"
import "context"

import (
	"log"
)

const (
	AlertStylePrimary   = "primary"
	AlertStyleSecondary = "secondary"
	AlertStyleSuccess   = "success"
	AlertStyleDanger    = "danger"
	AlertStyleWarning   = "warning"
	AlertStyleInfo      = "info"
)

type Alert struct {
	Style string
	Yield func()
}

func (c *Alert) writeClass(w io.Writer) {
	io.WriteString(w, "alert")

	switch c.Style {
	case AlertStylePrimary:
		io.WriteString(w, " alert--primary")
	case AlertStyleSecondary:
		io.WriteString(w, " alert--secondary")
	case AlertStyleSuccess:
		io.WriteString(w, " alert--success")
	case AlertStyleDanger:
		io.WriteString(w, " alert--danger")
	case AlertStyleWarning:
		io.WriteString(w, " alert--warning")
	case AlertStyleInfo:
		io.WriteString(w, " alert--info")
	default:
		log.Printf("Alert: invalid style: %q", c.Style)
	}
}

/*SCSS
.alert {
	position: relative;
	padding: .75rem 1.25rem;
	margin-bottom: 1rem;
	border: 1px solid transparent;
	border-radius: .25rem;

	&--primary {
		color: #004085;
		background-color: #cce5ff;
		border-color: #b8daff;
	}

	&--secondary {
		color: #464a4e;
		background-color: #e7e8ea;
		border-color: #dddfe2;
	}

	&--success {
		color: #155724;
		background-color: #d4edda;
		border-color: #c3e6cb;
	}

	&--danger {
		color: #721c24;
		background-color: #f8d7da;
		border-color: #f5c6cb;
	}

	&--warning {
		color: #856404;
		background-color: #fff3cd;
		border-color: #ffeeba;
	}

	&--info {
		color: #0c5460;
		background-color: #d1ecf1;
		border-color: #bee5eb;
	}
}
*/

func (c *Alert) Render(ctx context.Context, w io.Writer) {

//line http/component/alert.ego:91
	_, _ = io.WriteString(w, "<div class=\"")
//line http/component/alert.ego:91
	c.writeClass(w)
//line http/component/alert.ego:91
	_, _ = io.WriteString(w, "\">\n\t")
//line http/component/alert.ego:92
	if c.Yield != nil {
//line http/component/alert.ego:92
		c.Yield()
//line http/component/alert.ego:92
	}
//line http/component/alert.ego:93
	_, _ = io.WriteString(w, "\n</div>\n")
//line http/component/alert.ego:94
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
