// Generated by ego.
// DO NOT EDIT

//line component/error.ego:1
package component

import "fmt"
import "html"
import "io"
import "context"

type Error struct {
	Err error
}

func (c *Error) Render(ctx context.Context, w io.Writer) {

//line component/error.ego:11
	if c.Err != nil {
//line component/error.ego:12
		{
			egoComponent := Alert{
				Style: "danger",
				Yield: func() {
//line component/error.ego:13
				_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(c.Err.Error()))) },
			}
			egoComponent.Render(ctx, w)
		}
//line component/error.ego:15
	}
//line component/error.ego:17
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
